### ISSUE TITLE
Erreur ... (novice) 

### ISSUE THREAD

**Issue by renaud-bxl** [lovasoa/sanipasse#109]
Bonjour, 
Je suis novice et n'ai pas une grande expérience de Docker. J'arrive bien à faire tourner le script en localhost:80 mais je n'arrive à rien d'autre ... 

$ npm run dev me donne une erreur : 

```
Last login: Sat Nov 20 17:22:36 on ttys002
renaud@mbp-de-renaud-2 ~ % docker exec -it 7f8803596bf7071fdf92d0e8343aec2de07a2a21d1766fc612b6ebc91dc5fb67 /bin/sh
/code $ npm run dev

> sanipasse@1.5.5 dev
> svelte-kit dev

> EACCES: permission denied, mkdir '/code/.svelte-kit/dev/components'
Error: EACCES: permission denied, mkdir '/code/.svelte-kit/dev/components'
    at Object.mkdirSync (node:fs:1334:3)
    at mkdirp (file:///code/node_modules/@sveltejs/kit/dist/cli.js:221:15)
    at copy (file:///code/node_modules/@sveltejs/kit/dist/cli.js:250:3)
    at file:///code/node_modules/@sveltejs/kit/dist/cli.js:247:18
    at Array.forEach (<anonymous>)
    at copy (file:///code/node_modules/@sveltejs/kit/dist/cli.js:246:33)
    at file:///code/node_modules/@sveltejs/kit/dist/cli.js:247:18
    at Array.forEach (<anonymous>)
    at copy (file:///code/node_modules/@sveltejs/kit/dist/cli.js:246:33)
    at copy_assets (file:///code/node_modules/@sveltejs/kit/dist/cli.js:293:4)
file:///code/node_modules/@sveltejs/kit/dist/chunks/index.js:4409
			throw new Error('Cannot close server before it is initialized');
			      ^

Error: Cannot close server before it is initialized
    at Watcher.close (file:///code/node_modules/@sveltejs/kit/dist/chunks/index.js:4409:10)
    at process.<anonymous> (file:///code/node_modules/@sveltejs/kit/dist/chunks/index.js:4235:9)
    at process.emit (node:events:390:28)
    at process.emit (node:domain:475:12)
    at process.exit (node:internal/process/per_thread:184:15)
    at handle_error (file:///code/node_modules/@sveltejs/kit/dist/cli.js:798:10)
    at file:///code/node_modules/@sveltejs/kit/dist/cli.js:869:4
/code $ 
```

Comment accéder localement au localhost ou exporter le contenu du centenaire ? 

MILLES MERCI !

**Comment by lovasoa** [comment]
Bonjour,
  Je ne suis pas sûr de comprendre ce que vous essayez de faire: vous voulez contribuer à sanipasse, ou juste le faire tourner ?

Dans le premier cas, vous n'avez pas besoin de docker, dans le second, vous n'avez pas besoin de npm run dev. 

Je suppose que vous êtes dans le second cas. Vous avez alors juste besoin de la commande docker qui est inscrite dans le README de ce dépôt, rien de plus. Pas de docker exec, pas de npm run dev.

**Comment by lovasoa** [comment]
Et si vous êtes en fait dans le premier cas, et que vous voulez travailler sur le code de sanipasse, alors il vous faudra installer localement node et npm sur votre Mac (avec brew par exemple). Ensuite, vous pouvez lancer un npm install, puis un npm run dev directement depuis le répertoire sur lequel vous aurez cloné le dépôt de sanipasse.

**Comment by lovasoa** [comment]
Je ferme l'issue parce que ce n'est pas un bug dans sanipasse, mais vous pouvez toujours répondre ci-dessous.
