### ISSUE TITLE
erreur 500: Cannot read property 'default' of null

### ISSUE THREAD

**Issue by mamsedine** [lovasoa/sanipasse#55]
Merci de bien vouloir décrire ici votre appareil, votre navigateur, et les circonstances d'apparition du bug.

## Informations techniques

```
{
    "stack": "TypeError: Cannot read property 'default' of null\n    at eval (C:\\Users\\mam'script\\Documents\\GitHub\\sanipasse\\src\\routes\\index.svelte:25:61)\n    at Object.$$render (C:\\Users\\mam'script\\Documents\\GitHub\\sanipasse\\node_modules\\svelte\\internal\\index.js:1677:22)\n    at Object.default (/C:\\Users\\mam'script\\Documents\\GitHub\\sanipasse\\.svelte-kit\\dev/generated/root.svelte:59:127)\n    at Object.default (C:\\Users\\mam'script\\Documents\\GitHub\\sanipasse\\src\\routes\\__layout.svelte:62:50)\n    at eval (/node_modules/sveltestrap/src/Container.svelte:38:195)\n    at Object.$$render (C:\\Users\\mam'script\\Documents\\GitHub\\sanipasse\\node_modules\\svelte\\internal\\index.js:1677:22)\n    at eval (C:\\Users\\mam'script\\Documents\\GitHub\\sanipasse\\src\\routes\\__layout.svelte:61:124)\n    at Object.$$render (C:\\Users\\mam'script\\Documents\\GitHub\\sanipasse\\node_modules\\svelte\\internal\\index.js:1677:22)\n    at eval (/C:\\Users\\mam'script\\Documents\\GitHub\\sanipasse\\.svelte-kit\\dev/generated/root.svelte:57:122)\n    at $$render (C:\\Users\\mam'script\\Documents\\GitHub\\sanipasse\\node_modules\\svelte\\internal\\index.js:1677:22)"
}
```

**Comment by lovasoa** [comment]
Merci de bien vouloir décrire votre appareil, votre navigateur, et les circonstances d'apparition du bug.

**Comment by lovasoa** [comment]
Si vous ne rencontrez pas d'erreur avec sanipasse lui-même, mais avez des erreurs de uniquement en local pendant le développement avec sveltekit, vous pouvez les rapporter à svelte kit:

https://github.com/sveltejs/kit

**Comment by lovasoa** [comment]
Cette erreur ce produit aussi lorsque l'on n'a pas installé les dépendances du projet (avec `npm install`) avant de lancer `npm run dev`.
